# 开发环境配置
server:
  port: 3000
  host: localhost

database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: '123456'
  database: nest_production
  logging: true

app:
  name: 'Nest Ekko (Development)'
  debug: true