# 生产环境配置
server:
  port: 3000
  host: 0.0.0.0

database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: '123456'
  database: nest_production
  logging: false
  synchronize: false
  autoLoadEntities: true

app:
  name: 'Nest Ekko (Production)'
  debug: false